---
title: "Boot_ANOVA_V2"
author: "Chengyun Li"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(dplyr)
library(lmboot)
library(boot)
library(knitr)
load("Paper2_3.RData")
```

```{r, include=FALSE}
bootstrap_data <- exdat_eval %>%
  mutate(Exposure = factor(case_when(exposure_k == "4 - Unexposed" ~ "Unexposed",
                                     exposure_k == "3 - Low Exposure" ~ "Low Exposure",
                                     exposure_k == "2 - High Exposure" ~ "High Exposure"), 
                           levels = c("Unexposed", "Low Exposure", "High Exposure")),
         Concussion = pre_con, # 0, 1-2, 3+
         Concussion.history.1 = con_hist1, # 0, 1, 2, 3+
         Concussion.history.2 = con_hist2, # 0, 1, 2+
         Year_part = as.numeric(Year_part)
         )

outcome_names <- c("SWLS_TOTALSCORE", "Neuro_QoL", "SF12_Mental", "SF12_Physical", "AUDIT", "PSQI(insomnia)", "PHQ9(Psychometric)", "NSI(Neurobehavioral)")
outcomes <- c("SWLS_TOTALSCORE", "NQLCD_TSCORE", "SF12MCS", "SF12PCS", "AUDIT_TOTALSCORE", "PSQITOTALSCORE", "PHQ9_TOTALSCORE", "NSISCORE")
```

## Table1. Three-way interactions
```{r, include=FALSE}
boot_ANOVA_3way_df <- data.frame(
  col1 = numeric(0),
  col2 = numeric(0),
  col3 = numeric(0),
  col4 = numeric(0),
  col5 = numeric(0),
  col6 = numeric(0),
  col7 = numeric(0)
)
boot_ANOVA_3way <- function(data, outcome){
  boot_ANOVA_data <- data %>%
  select(outcome, Exposure, Concussion, Year_part) %>%
  na.omit()
  
  myANOVA <- ANOVA.boot(as.formula(paste(outcome, "~ Exposure*Concussion*Year_part")), B=4000, data=boot_ANOVA_data)
  return(myANOVA)
}

for(outcome in outcomes){
  myANOVA_result <- boot_ANOVA_3way(data=bootstrap_data, outcome=outcome)
  boot_ANOVA_3way_df <- rbind(boot_ANOVA_3way_df, myANOVA_result$`p-values`)
  interactions <- myANOVA_result$terms
}
colnames(boot_ANOVA_3way_df) <- interactions[-length(interactions)]
rownames(boot_ANOVA_3way_df) <- outcome_names
kable(boot_ANOVA_3way_df, digits=4, format = "markdown")
```


## Table1*. Two-way interactions
```{r, warning=FALSE, echo=FALSE}
boot_ANOVA_3way_df <- data.frame(
  col1 = numeric(0),
  col2 = numeric(0),
  col3 = numeric(0),
  col4 = numeric(0),
  col5 = numeric(0),
  col6 = numeric(0)
)
boot_ANOVA_3way <- function(data, outcome){
  boot_ANOVA_data <- data %>%
  select(outcome, Exposure, Concussion, Year_part) %>%
  na.omit()
  
  myANOVA <- ANOVA.boot(as.formula(paste(outcome, "~ Exposure*Concussion + Exposure*Year_part + Concussion*Year_part")), B=4000, data=boot_ANOVA_data)
  return(myANOVA)
}

for(outcome in outcomes){
  myANOVA_result <- boot_ANOVA_3way(data=bootstrap_data, outcome=outcome)
  boot_ANOVA_3way_df <- rbind(boot_ANOVA_3way_df, myANOVA_result$`p-values`)
  interactions <- myANOVA_result$terms
}
colnames(boot_ANOVA_3way_df) <- interactions[-length(interactions)]
rownames(boot_ANOVA_3way_df) <- outcome_names
kable(boot_ANOVA_3way_df, digits=4, format = "markdown")
```

## Table2. Two-way interactions(Exposure:Concussion)
```{r, include=FALSE}
boot_ANOVA_EC_df <- data.frame(
  col1 = numeric(0),
  col2 = numeric(0),
  col3 = numeric(0)
)
boot_ANOVA_EC <- function(data, outcome){
  boot_ANOVA_data <- data %>%
  select(outcome, Exposure, Concussion) %>%
  na.omit()
  
  myANOVA <- ANOVA.boot(as.formula(paste(outcome, "~ Exposure*Concussion")), B=4000, data=boot_ANOVA_data)
  return(myANOVA)
}

for(outcome in outcomes){
  myANOVA_result <- boot_ANOVA_EC(data=bootstrap_data, outcome=outcome)
  boot_ANOVA_EC_df <- rbind(boot_ANOVA_EC_df, myANOVA_result$`p-values`)
  interactions <- myANOVA_result$terms
}
colnames(boot_ANOVA_EC_df) <- interactions[-length(interactions)]
rownames(boot_ANOVA_EC_df) <- outcome_names
kable(boot_ANOVA_EC_df, digits=4, format = "markdown")
```



## Table3. Two-way interactions (Exposure:Year_part)
```{r, include=FALSE}
boot_ANOVA_EY_df <- data.frame(
  col1 = numeric(0),
  col2 = numeric(0),
  col3 = numeric(0)
)
boot_ANOVA_EY <- function(data, outcome){
  boot_ANOVA_data <- data %>%
  select(outcome, Exposure, Year_part) %>%
  na.omit()
  
  myANOVA <- ANOVA.boot(as.formula(paste(outcome, "~ Exposure*Year_part")), B=4000, data=boot_ANOVA_data)
  return(myANOVA)
}

for(outcome in outcomes){
  myANOVA_result <- boot_ANOVA_EY(data=bootstrap_data, outcome=outcome)
  boot_ANOVA_EY_df <- rbind(boot_ANOVA_EY_df, myANOVA_result$`p-values`)
  interactions <- myANOVA_result$terms
}
colnames(boot_ANOVA_EY_df) <- interactions[-length(interactions)]
rownames(boot_ANOVA_EY_df) <- outcome_names
kable(boot_ANOVA_EY_df, digits=4, format = "markdown")
```



## Table4. Two-way interactions(Concussion:Year_part)
```{r, include=FALSE}
boot_ANOVA_CY_df <- data.frame(
  col1 = numeric(0),
  col2 = numeric(0),
  col3 = numeric(0)
)
boot_ANOVA_CY <- function(data, outcome){
  boot_ANOVA_data <- data %>%
  select(outcome, Concussion, Year_part) %>%
  na.omit()
  
  myANOVA <- ANOVA.boot(as.formula(paste(outcome, "~ Concussion*Year_part")), B=4000, data=boot_ANOVA_data)
  return(myANOVA)
}

for(outcome in outcomes){
  myANOVA_result <- boot_ANOVA_CY(data=bootstrap_data, outcome=outcome)
  boot_ANOVA_CY_df <- rbind(boot_ANOVA_CY_df, myANOVA_result$`p-values`)
  interactions <- myANOVA_result$terms
}
colnames(boot_ANOVA_CY_df) <- interactions[-length(interactions)]
rownames(boot_ANOVA_CY_df) <- outcome_names
kable(boot_ANOVA_CY_df, digits=4, format = "markdown")
```


